### ISSUE TITLE
Rework linux/osx support plus new simplified format?

### ISSUE THREAD

**Issue by goanpeca** [conda/menuinst#48]
@kalefranz, @msarahan, @mingwandroid 

I have been wanting to update the linux/osx support for some time, but it might also be a good opportunity to reevaluate the current format. Since conda uses jinja2, yaml and selectors, it would be pretty natural to do the same for menuinst (lets say version 2.0):

Based on https://github.com/ContinuumIO/menuinst/wiki/Menu-Shortcut-Config-Structure

Could we turn the format into yaml, and use jinja2 and selectors, and make it more uniform among all OSs? We could still use separate files for separate OSs, but we could just have one file that knows what to do everywhere

This would create subfolders for environments and no subfolder for the root (hopefully). Overriding the creation for other envs, should probably be handed by the CLI when called, instead of including the info inside this file

```
../conda.recipe/
   menu.yaml
   icons/
      someicon.ico
      someicon.icns
```
```yaml
{% set BASE_DIR = 'Anaconda'PY_VER PLATFORM %}
{% set ICO_EXT = 'ico' if WIN or LINUX else 'icns' %}

version: 2.0
menu:
  - path: {% if ROOT_PREFIX != ENV_PREFIX %}{{ BASE_DIR }}/{{ ENVNAME }}{% else %}{{ BASE_DIR }}{{% endif %}
    shortcuts:
      - name: 'SomeApp'
        version: 1.8.9
        cmd:    #  Or we can split cmd, and args...
          - '{{ PYTHONW }}'
          - '{{ PYTHON_SCRIPTS }}/someapp'
        comment: 'Some description of someapp'
        icon: '{{ MENU_DIR }}/someicon.{{ ICO_EXT }}'
        icon_path: 'icons/someicon.{{ ICO_EXT }}'
        desktop: True                         # [win]
        quicklaunch: True                     # [linux and win]
```

```
# Check the need of keys
terminal
id

# "new" env variables
FILEBROWSER
WEBBROWSER
CMD/BASH ?

# deprecate keys
icns 
pywscript
pyscript
script
scriptarguments
system
webbrowser
```

Plus adding a programmatic api `menuinst.api` 
```python
from menuninst.api import Menu, Shortcut

menu = Menu('My awesome thing/submenu/')
shortcut = Shortcut('App', ['command'], desktop=True, icon=None)
shortcut.icon = '{{ MENU_DIR }}/icon.ico'
shortcut.icon_path = 'icons/icon.ico'
menu.add(shortcut)
menu.install(context={...})
menu.uninstall(...)
yaml_data = menu.to_yaml()
json_data = menu.to_json()
```

Thoughts?
